Repository sqrldev/SQRLDotNetClient, pull requests merged in 2020-01, with the labels that each got.

#2 WIP: Improve identity parsing
  SQRLConsoleTester/Program.cs
  SQRLUtilsLib/SQRL.cs
  SQRLUtilsLib/SQRLIdentity.cs
Labels: enhancement, good first issue

#10 WIP: Add Github CI
  .github/workflows/dotnetcore.yml
  SQRLUtilsLib/SQRLUtilsLib.csproj
  Sodium.Core/Sodium.Core.ForSqrl.csproj
Labels: work in progress

#11 Added Test Step ( I Think)
  .github/workflows/dotnetcore.yml
Labels: enhancement

#14 Adding siport for SIN , PSIN (WIP)
  SQRLUtilsLib/SQRLServerResponse.cs
Labels: work in progress
